import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "primeicons/primeicons.css";
import "primereact/resources/themes/lara-dark-indigo/theme.css";

import PrimeProvider from "@/components/PrimeReactProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        <link
          id="theme-link"
          rel="stylesheet"
          href="/themes/lara-dark-indigo/theme.css"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PrimeProvider>
          <div className="bg-surface-ground">{children}</div>
        </PrimeProvider>
      </body>
    </html>
  );
}
